# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-self-distilled-gan
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - opencv
  - pip:
    - addict
    - future
    - numpy
    - Pillow
    - pyyaml
    - requests
    - scikit-image
    - scipy
    - torch>=1.9
    - torchvision
    - timm
    - einops
    - youtube-dl
    - matplotlib